### ISSUE TITLE
Fresh build fails on CentOS 7.1

### ISSUE THREAD

**Issue by llamahunter** [pinterest/secor#122]
There appears to be something wrong wit the pom.xml file.  A number of warnings are emitted, and then the build fails unable to find the com.twitter.finagle.thrift package.
```
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.pinterest:secor:jar:0.2-SNAPSHOT
[WARNING] 'build.plugins.plugin.(groupId:artifactId)' must be unique but found duplicate declaration of plugin org.codehaus.mojo:exec-maven-plugin @ line 269, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 

...

[WARNING] Checksum validation failed, no checksums available from the repository for http://maven.twttr.com/org/apache/thrift/libthrift/0.5.0/libthrift-0.5.0.pom

...

[WARNING] Checksum validation failed, no checksums available from the repository for http://maven.twttr.com/thrift/libthrift/0.5.0/libthrift-0.5.0.jar

...

[ERROR] COMPILATION ERROR : 
[ERROR] /home/build/jenkins_tempdir/workspace/secor/target/generated-sources/thrift/gen-java/com/pinterest/secor/thrift/TestMessage.java:[35,33] error: package com.twitter.finagle.thrift does not exist
```

Oddly, it appears to build without incident on OSX 10.10.5

**Comment by HenryCaiHaiying** [comment]
I saw those plugin warnings in my local build, but that doesn't stop the
compilation.  I don't see any problems downloading that libthrift:

[INFO] --- maven-finagle-thrift-plugin:0.0.9:compile (thrift-sources) @
secor ---

Downloading:
https://mavenrepo-external.pinadmin.com/thirdparty/thrift/libthrift/0.5.0/libthrift-0.5.0.pom


What's your mvn version?  Mine is 3.3.1

**Comment by llamahunter** [comment]
After much experimenting with maven versions, I’ve gotten it to build using maven 3.0.4.  I was previously using 3.2.2.  I did not try 3.3.1, but did try 3.3.3.  Did not build due to some sort of catastrophic type resolution error.

Seems like the pom is very maven-version sensitive.

Richard
Key ID: 3BDED925D4F316B3
